apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:

      # mongo
      - name: mongo
        image: mongo:3

      # elastic
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.2
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: http.host
          value: "0.0.0.0"

      # graylog
      - name: graylog
        image: graylog/graylog:3.0.1-1
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: somepasswordpepper
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: http://local.o12stack.org/
        - name: GRAYLOG_MONGODB_URI
          value: mongodb://localhost:27017/graylog
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: http://localhost:9200
        - name: GRAYLOG_ROTATION_STRATEGY
          value: time
        - name: GRAYLOG_ELASTICSEARCH_MAX_TIME_PER_INDEX
          value: "1d"
        - name: GRAYLOG_ELASTICSEARCH_MAX_NUMBER_OF_IINDICES
          value: "10"
        - name: GRAYLOG_ELASTICSEARCH_INDEX_PREFIX
          value: "graylog"
        - name: GRAYLOG_ELASTICSEARCH_SHARDS
          value: "1"

