# Filebeat daemon set
# A 'daemon set' runs on each node of a K8s cluster
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      # see filebeat-rbac.yml
      serviceAccountName: filebeat-serviceaccount
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.7.2
        # to read host's /var/lib/docker/containers
        # this container needs to run under root
        securityContext:
          runAsUser: 0
        volumeMounts:
        # volume that contains the config
        - name: filebeat-configuration
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        # mapping of host's docker container dir (R/O!) to read the logs
        - name: docker-host-container-dir
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: filebeat-configuration
        configMap:
          defaultMode: 0644
          name: filebeat-configuration
      - name: docker-host-container-dir
        hostPath:
          path: /var/lib/docker/containers
